# Generated by Django 3.2.4 on 2021-07-09 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('topic', models.CharField(choices=[('array', 'Arrays'), ('dp', 'Dynamic Programing'), ('string', 'Strings'), ('maths', 'Maths'), ('greedy', 'Greedy'), ('dfs', 'DFS'), ('tree', 'Tree'), ('hash table', 'Hash Table'), ('binary search', 'Binary Search'), ('bfs', 'BFS'), ('two pointer', 'Two Pointer'), ('backtracking', 'BackTracking'), ('stack', 'Stack'), ('design', 'Design'), ('graph', 'Graph'), ('bit', 'Bit Manipulation'), ('linked list', 'Linked List'), ('heap', 'HEAP'), ('sliding window', 'Sliding Window'), ('trie', 'trie'), ('segment tree', 'Segment Tree')], max_length=15)),
                ('level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('tutorial', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
