# Generated by Django 3.2.4 on 2021-07-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionList', '0002_auto_20210709_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quedonebyuser',
            old_name='user',
            new_name='owner',
        ),
    ]
